name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests and save logs
        run: |
          python -m unittest discover -s . -p "unit_tests.py" | tee test_log.txt

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.os }}
          path: test_log.txt


      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "unit_tests.py"
